Embedly Preview
===============
Embedly Preview is a jQuery plugin that allows developers to create tools that
enable users to share links with rich previews attached. This method of letting
users select thumbnails, edit title and description has been adopted as the
norm across the web. This plugin allows users to easily implement this
functionality without building the entire infrastructure themselves, instead
relying on on Embedly to generate the metadata.

We have made this plugin overly verbose and infinitely customizable. Our goal
is not to dictate design, merely give a set of tools to make it easy to create
a custom experience. There are X different demos that you should take a look at
before getting started. It will give you a quick overview of what you should be
able to build.

* `Status`  
* `Link`

Basic Setup
===========
To get started you need to throw `jQuery <http://jquery.com/>`_, `Underscore.js
<http://documentcloud.github.com/underscore/>`_, jquery.preview.js and the
preview.css.

    <head>
      <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
      <script src="lib/underscore-min.js" type="text/javascript"></script>
      <script src="jquery.preview.js" type="text/javascript"></script>
      <link rel="stylesheet" href="preview.css" />
    </head>

Next set up a simple form that allows a user to input link::

    <form action="/update" method="POST">
        <textarea id="status"></textarea>
    </form>
    
Next you need to tell preview what field to listen to::

    <script>
        $('#status').preview({key:'your_embedly_key'})
    </script>

And you are done setting up the front end solution for Embedly Preview. The
rest of this document will go into how to customize Preview.

Objects
=======
There are 3 basic objects that you should get familiar with in order to
customize the selector. 

Preview
=======
Preview holds all the logic for calls to embedly.


Selector
========
Builds the selector

Feed
====
Create's feed objects.



